name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if locked part of maintenance is in progress
        uses: ./.github/actions/wait-for-workflows-to-finish
        with:
          # lock-workflow id
          workflow_ids: "128058478"
          timeout: 300
          delay: 5
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: echo "Running tests" && sleep 60
