name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if locked part of maintenance is in progress
        uses: ./.github/actions/lock-branch
        with:
          timeout: 300
          delay: 5
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: 'wait'
      - name: Build
        id: build
        run: |
          echo "somevar=$(echo -e 'one\ntwo\nthree' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run tests
        run: |
          echo ${{ steps.build.outputs.somevar }}
          echo "looping through the output..."
          for i in ${{ steps.build.outputs.somevar }}; do
            echo $i
          done
