name: maintenance

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/lock-workflow.yaml
    with:
      workflow_ids: '127898300'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: maintenance work
        run: |
          echo "Outputs from lock workflow"
          echo "${{ needs.job1.outputs.firstword }}"
          echo "${{ needs.job1.outputs.secondword }}"
          sleep 60
